services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - '27018:27017'
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - instagram-server_mongodata:/data/db

volumes:
  instagram-server_mongodata:
    external: true
