services:
  nest-server:
    build: .
    container_name: nest-server
    command: yarn start:dev
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - instagram-server_mongodata:/data/db

volumes:
  instagram-server_mongodata:
    external: true
